# Generated by Django 3.2 on 2021-06-14 13:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255),
        ),
    ]
