# Generated by Django 3.2 on 2021-06-14 17:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=cloudinary.models.CloudinaryField(default='banner_default.jpg', max_length=255),
        ),
    ]
