# Generated by Django 3.2 on 2021-06-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_social',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_social',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedIn_social',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_social',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
