# Generated by Django 3.2 on 2021-06-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_social',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_social',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedIn_social',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_social',
        ),
    ]
