# Generated by Django 3.2 on 2021-06-19 12:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210619_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=cloudinary.models.CloudinaryField(default='banner_default.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255),
        ),
    ]
