# Generated by Django 3.2 on 2021-05-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='name',
        ),
    ]
