# Generated by Django 3.2 on 2021-07-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_liked_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
    ]
