# Generated by Django 3.2 on 2021-07-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_category_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='archive',
        ),
    ]
