# Generated by Django 3.2 on 2021-06-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_fashion_lifestyle_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashion',
            name='name',
        ),
        migrations.AddField(
            model_name='fashion',
            name='fashion_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post'),
        ),
    ]
