# Generated by Django 3.2 on 2021-06-08 13:23

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210608_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashion',
            name='fashion_post',
        ),
        migrations.AddField(
            model_name='fashion',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AddField(
            model_name='fashion',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fashion',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='fashion',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fashion',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fashion',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fashion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='fashion',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Fashion_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.fashion'),
        ),
    ]
