# Generated by Django 3.2 on 2021-06-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210608_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifestyle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Fashion_post',
        ),
        migrations.DeleteModel(
            name='Fashion',
        ),
        migrations.DeleteModel(
            name='Lifestyle',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
