# Generated by Django 3.2 on 2021-07-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_like_post_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='text',
        ),
        migrations.AlterField(
            model_name='archive',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
