# Generated by Django 3.2 on 2021-07-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_archive_post_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archive',
            new_name='Club',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='club',
        ),
    ]
