# Generated by Django 3.2 on 2021-06-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='location',
        ),
    ]
